name: Sync to Gitee

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Sync to Gitee
        run: |
          git remote add gitee https://oauth2:${{ secrets.GITEE_TOKEN }}@gitee.com/hzzxcgtz/classnode.git
          git push --force --prune gitee
